# Generated by Selenium IDE
import pytest
from fixture.application import Application

@pytest.fixture
def app(request):
  fixture = Application()
  request.addfinalizer(fixture.destroy)
  return fixture

def test_add_comment(app):
  app.session.login(username = '+79210120011', password= 'Anika777')
  #app.create_comment(Comment())
  app.session.logout()



