# Generated by Selenium IDE
import pytest
from aplication import Application

@pytest.fixture
def app(request):
  fixture = Application()
  request.addfinalizer(fixture.destroy)
  return fixture

def test_add_comment(app):
  app.login(username = '+79210120011', password= 'Anika777')
  #app.create_comment(Comment())
  app.logout()



