# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    self.driver.get("https://coredemo.apdow.net/")
    self.driver.set_window_size(2490, 1376)
    self.driver.find_element(By.LINK_TEXT, "HIPHOTO").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.NAME, "email").send_keys("79210120013")
    self.driver.find_element(By.NAME, "password").send_keys("Anika777")
    self.driver.find_element(By.LINK_TEXT, "Create an Account").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-3 > .ng-untouched").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-3 > .ng-untouched")
    dropdown.find_element(By.XPATH, "//option[. = 'Russia']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-4 > .ng-untouched").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-4 > .ng-untouched").send_keys("921")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-4 > .ng-invalid").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c92-4 > .ng-dirty").send_keys("9210120090")
    self.driver.find_element(By.CSS_SELECTOR, "app-card-actions-processing-buttons:nth-child(5) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-5").send_keys("320279")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted > .flex-fill > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-6").send_keys("79210120089@mm.mm")
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-7").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-7").send_keys("Anika777")
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-8").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-main > .ng-tns-c92-8").send_keys("Aaaa")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched:nth-child(1)").send_keys("Dddd")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-calendar > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(5) > .mat-calendar-body-cell-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "app-card-actions-processing-buttons:nth-child(10) .btn").click()
  
